/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations = {
  en: {
    brand: "AGRO VISION",
    home: "Home",
    dashboard: "Dashboard",
    cropRec: "Crop Recommendation",
    profile: "Profile",
    login: "Login",
    signup: "Sign Up",
    logout: "Log Out",
    welcome: "Welcome to AGRO VISION",
    heroSubtitle: "Empowering agriculture with state-of-the-art AI disease diagnostics and real-time weather crop matching.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    weather: "Live Weather",
    diseaseScanner: "AI Disease Detection",
    cropMatcher: "AI Crop Matching",
    scanHistory: "Scan History",
    cropHistory: "Crop Matches",
    treatmentHistory: "Treatments",
    statistics: "AI Performance Metrics",
    quickActions: "Quick Actions",
    joinedDate: "Joined Date",
    username: "Username",
    email: "Email Address",
    password: "Password",
    saveChanges: "Save Changes",
    noHistory: "No records found.",
    loading: "Loading AGRO VISION systems...",
    
    // Scanner
    scanTitle: "AI Plant Disease Diagnostics",
    scanDrop: "Drag & drop a crop photo, or click to browse",
    scanFormats: "Supports JPG, JPEG, PNG",
    scanLoading: "Analyzing crop health...",
    scanProgress1: "Detecting disease patterns...",
    scanProgress2: "Generating farming insights...",
    scanBtn: "Scan Crop",
    resultTitle: "Diagnostic Report",
    diseaseName: "Detected Disease",
    confidence: "Confidence Level",
    cropType: "Crop Type",
    severity: "Severity",
    summary: "AI Diagnosis Summary",
    treatmentBtn: "View AI Treatment Plan",
    pesticides: "Recommended Pesticides",
    fertilizers: "Recommended Fertilizers",
    organic: "Organic Treatment",
    watering: "Watering Advice",
    prevention: "Prevention Tips",
    recovery: "Recovery Timeline",
    close: "Close",

    // Crop Rec
    cropRecTitle: "Smart Crop Recommendation",
    cropRecSubtitle: "Analyze live atmospheric conditions to recommend ideal crops.",
    locationPlaceholder: "Enter City or Region (e.g., Guntur, Hyderabad)",
    analyzeBtn: "Analyze Live Weather & Suggest Crops",
    analyzing: "Analyzing local microclimates...",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Precipitation",
    windSpeed: "Wind Speed",
    weatherCondition: "Weather Condition",
    recommendationTitle: "AI Agronomist Crop Match Analysis",
    farmingRisks: "Farming Risks",
    waterReq: "Water Requirements",
    whySuitable: "Suitability Context",
    searchHistory: "Search History",
    filterType: "Filter Results",
    all: "All",
    scans: "Scans",
    crops: "Crops",
    delete: "Delete",
    clearFilters: "Clear Filters",
    confirmDelete: "Are you sure you want to delete this record?",
  },
  te: {
    brand: "అగ్రో విజన్",
    home: "హోమ్",
    dashboard: "డాష్‌బోర్డ్",
    cropRec: "పంట సిఫార్సు",
    profile: "ప్రొఫైల్",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగ్ అవుట్",
    welcome: "అగ్రో విజన్ కు స్వాగతం",
    heroSubtitle: "అత్యాధునిక కృత్రిమ మేధస్సు (AI) మరియు ప్రత్యక్ష వాతావరణ ఆధారిత పంట సిఫార్సులతో వ్యవసాయాన్ని బలోపేతం చేయడం.",
    getStarted: "ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    weather: "ప్రత్యక్ష వాతావరణం",
    diseaseScanner: "AI వ్యాధి నిర్ధారణ",
    cropMatcher: "AI పంట పోలిక",
    scanHistory: "స్కాన్ చరిత్ర",
    cropHistory: "పంట సిఫార్సులు",
    treatmentHistory: "చికిత్సలు",
    statistics: "AI పనితీరు గణాంకాలు",
    quickActions: "త్వరిత చర్యలు",
    joinedDate: "చేరిన తేదీ",
    username: "వినియోగదారు పేరు",
    email: "ఈమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    saveChanges: "మార్పులను సేవ్ చేయి",
    noHistory: "ఎటువంటి రికార్డులు లేవు.",
    loading: "అగ్రో విజన్ సిస్టమ్స్ లోడ్ అవుతున్నాయి...",
    
    // Scanner
    scanTitle: "AI పంట వ్యాధి నిర్ధారణ",
    scanDrop: "పంట ఫోటోను ఇక్కడ లాగండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
    scanFormats: "JPG, JPEG, PNG ఫార్మాట్లకు మద్దతు ఇస్తుంది",
    scanLoading: "పంట ఆరోగ్యాన్ని విశ్లేషిస్తోంది...",
    scanProgress1: "వ్యాధి నమూనాలను గుర్తిస్తోంది...",
    scanProgress2: "వ్యవసాయ అంతర్దృష్టులను సృష్టిస్తోంది...",
    scanBtn: "పంట స్కాన్ చేయి",
    resultTitle: "వ్యాధి విశ్లేషణ నివేదిక",
    diseaseName: "గుర్తించిన వ్యాధి",
    confidence: "విశ్వసనీయత స్థాయి",
    cropType: "పంట రకం",
    severity: "తీవ్రత",
    summary: "AI నిర్ధారణ సారాంశం",
    treatmentBtn: "AI చికిత్సా ప్రణాళిక",
    pesticides: "సిఫార్సు చేసిన పురుగుమందులు",
    fertilizers: "సిఫార్సు చేసిన ఎరువులు",
    organic: "సేంద్రీయ చికిత్స",
    watering: "నీటి యాజమాన్యం",
    prevention: "నివారణ చిట్కాలు",
    recovery: "కోలుకునే సమయం",
    close: "మూసివేయి",

    // Crop Rec
    cropRecTitle: "తెలివైన పంట సిఫార్సు",
    cropRecSubtitle: "ఆదర్శవంతమైన పంటలను సూచించడానికి ప్రత్యక్ష వాతావరణ పరిస్థితులను విశ్లేషించండి.",
    locationPlaceholder: "నగరం లేదా ప్రాంతాన్ని నమోదు చేయండి (ఉదా. గుంటూరు, హైదరాబాద్)",
    analyzeBtn: "వాతావరణాన్ని విశ్లేషించి పంటలను సూచించండి",
    analyzing: "స్థానిక వాతావరణాన్ని విశ్లేషిస్తోంది...",
    temperature: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    rainfall: "వర్షపాతం",
    windSpeed: "గాలి వేగం",
    weatherCondition: "వాతావరణ పరిస్థితి",
    recommendationTitle: "AI వ్యవసాయ శాస్త్రవేత్త పంట విశ్లేషణ",
    farmingRisks: "వ్యవసాయ ప్రమాదాలు",
    waterReq: "నీటి అవసరాలు",
    whySuitable: "అనుకూలత కారణం",
    searchHistory: "చరిత్ర శోధన",
    filterType: "ఫిల్టర్ రకం",
    all: "అన్నీ",
    scans: "స్కాన్లు",
    crops: "పంటలు",
    delete: "తొలగించు",
    clearFilters: "ఫిల్టర్లు తొలగించు",
    confirmDelete: "ఈ రికార్డును మీరు ఖచ్చితంగా తొలగించాలనుకుంటున్నారా?",
  },
  hi: {
    brand: "एग्रो विज़न",
    home: "होम",
    dashboard: "डैशबोर्ड",
    cropRec: "फसल सिफारिश",
    profile: "प्रोफ़ाइल",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉग आउट",
    welcome: "एग्रो विज़न में आपका स्वागत है",
    heroSubtitle: "अत्याधुनिक कृत्रिम बुद्धिमत्ता (AI) रोग निदान और वास्तविक समय मौसम फसल मिलान के साथ कृषि को सशक्त बनाना।",
    getStarted: "शुरू करें",
    learnMore: "अधिक जानें",
    weather: "लाइव मौसम",
    diseaseScanner: "AI रोग निदान",
    cropMatcher: "AI फसल मिलान",
    scanHistory: "स्कैन इतिहास",
    cropHistory: "फसल सिफारिशें",
    treatmentHistory: "उपचार",
    statistics: "AI प्रदर्शन मेट्रिक्स",
    quickActions: "त्वरित कार्रवाई",
    joinedDate: "जुड़ने की तिथि",
    username: "उपयोगकर्ता नाम",
    email: "ईमेल पता",
    password: "पासवर्ड",
    saveChanges: "बदलाव सहेजें",
    noHistory: "कोई रिकॉर्ड नहीं मिला।",
    loading: "एग्रो विज़न सिस्टम लोड हो रहा है...",
    
    // Scanner
    scanTitle: "AI फसल रोग निदान",
    scanDrop: "फसल की तस्वीर खींचें या फ़ाइल अपलोड करने के लिए क्लिक करें",
    scanFormats: "JPG, JPEG, PNG का समर्थन करता है",
    scanLoading: "फसल स्वास्थ्य का विश्लेषण किया जा रहा है...",
    scanProgress1: "रोग के लक्षणों की पहचान की जा रही है...",
    scanProgress2: "कृषि अंतर्दृष्टि तैयार की जा रही है...",
    scanBtn: "फसल स्कैन करें",
    resultTitle: "रोग निदान रिपोर्ट",
    diseaseName: "पहचाना गया रोग",
    confidence: "आत्मविश्वास स्तर",
    cropType: "फसल का प्रकार",
    severity: "तीव्रता",
    summary: "AI निदान सारांश",
    treatmentBtn: "AI उपचार योजना देखें",
    pesticides: "अनुशंसित कीटनाशक",
    fertilizers: "अनुशंसित उर्वरक",
    organic: "जैविक उपचार",
    watering: "सिंचाई सलाह",
    prevention: "बचाव के उपाय",
    recovery: "ठीक होने की अवधि",
    close: "बंद करें",

    // Crop Rec
    cropRecTitle: "स्मार्ट फसल सिफारिश",
    cropRecSubtitle: "आदर्श फसलों की सिफारिश करने के लिए लाइव मौसम की स्थिति का विश्लेषण करें।",
    locationPlaceholder: "शहर या क्षेत्र दर्ज करें (जैसे, गुंटूर, हैदराबाद)",
    analyzeBtn: "मौसम का विश्लेषण करें और फसल सुझाएं",
    analyzing: "स्थानीय सूक्ष्म जलवायु का विश्लेषण किया जा रहा है...",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rainfall: "वर्षा",
    windSpeed: "हवा की गति",
    weatherCondition: "मौसम की स्थिति",
    recommendationTitle: "AI कृषि विशेषज्ञ फसल मिलान विश्लेषण",
    farmingRisks: "कृषि जोखिम",
    waterReq: "पानी की आवश्यकता",
    whySuitable: "उपयुक्तता का संदर्भ",
    searchHistory: "इतिहास खोजें",
    filterType: "फ़िल्टर प्रकार",
    all: "सभी",
    scans: "स्कैन",
    crops: "फसलें",
    delete: "हटाएं",
    clearFilters: "फ़िल्टर साफ करें",
    confirmDelete: "क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?",
  }
};

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('agro_vision_locale') || 'en';
  });

  const changeLanguage = (lang) => {
    setLocale(lang);
    localStorage.setItem('agro_vision_locale', lang);
  };

  const t = (key) => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
